server:
  port: 8080
#  port: 9192
 
jwt:
  secret:
    key:
      users:
        access_token: ${JWT_USER_TOKEN}
        expiration: 86400000  # for a day
        refresh_token:
          expiration: 604800000 # for 7 days     
      message: ${JWT_MESSAGE_TOKEN}
      admin: ${JWT_ADMIN_TOKEN}
      products: ${JWT_PRODUCTS_TOKEN}

#this for message sent , to add domain link
website:
  domain:
    url:
      user: ${USER_DOMAIN_URL}
      #user: http://localhost:4401


cors:
  set:
    allowed:
      origins: ${USER_CORS_LINK_1},
               ${USER_CORS_LINK_2}
               
filter:
  url:
    patterns: /pckart/api/v1/user-to-admin/user/*,
              /pckart/api/v1/user-to-admin/coupon/*
              /pckart/api/v1/user-to-admin/order/*
              
#this for return from user jwt authentication because it's from admin  
user:
  request:
    uri: /pckart/api/v1/user-to-admin

product:
  service:
    api:
      url:
        get-quantity-byid: ${PRODUCT_APP_DOMAIN}/pckart/api/v1/products/get/quantity/
        change-products-quantity: ${PRODUCT_APP_DOMAIN}/pckart/api/v1/products/auth/change-products-quantity
  
  
razorpay: 
  api:
    key: ${RAZORPAY_KEY}
    key_secret: ${RAZORPAY_KEY_SECRET}
    currency: ${RAZORPAY_CURRENCY}
  
